version: "3"

networks:
  app-networks:
services:
  theralink:
    container_name: "theralink"
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "4001:4000"
    environment:
      - PORT=4000

    env_file:
      - .env
